POST http://localhost:8888/api/user/saveBatch
Content-Type: application/json

[
{
   "createdTime" : "2023-02-24 10:11:08",
    "createdBy" : null,
    "updatedTime" : "2023-02-24 10:11:08",
    "updatedBy" : null,
    "username" : {{$timestamp}},
    "mobile" : "19999999903"
}, {"createdTime" : "2023-02-24 10:11:08",
    "createdBy" : null,
    "updatedTime" : "2023-02-24 10:11:08",
    "updatedBy" : null,
    "username" : {{$timestamp}},
    "mobile" : "19999999904"
}
]

###
POST http://localhost:8888/api/user/delete
Content-Type: application/json

{
  "id": "9731018007248896"
}

###
POST http://localhost:8888/api/user/update
Content-Type: application/json

{
  "id": "9731018007248896",
  "mobile": "18899999908"
}

###
POST http://localhost:8888/api/user/save
Content-Type: application/json

{
    "createdTime" : "2023-02-24 10:11:08",
    "createdBy" : null,
    "updatedTime" : "2023-02-24 10:11:08",
    "updatedBy" : null,
    "username" : {{$timestamp}},
    "mobile" : "19999999902"
  }

###
GET http://localhost:8888/api/user/info
Content-Type: application/json
#trace-id: "sssessssssjieowejwe"

{
  "username": "gyw"
}

###
GET http://localhost:8888/api/user/list
Content-Type: application/json

{
}

###
GET http://localhost:8888/api/user/pages
Content-Type: application/json

{
}




