server:
  port: 8888
  contextPath: /vertx
http:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
dataSource:
  driverClassName: "com.mysql.jdbc.Driver"
  port: 3307
  host: "localhost"
  database: vertx
  jdbcUrl: "jdbc:mysql://localhost:3307/vertx?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&tinyInt1isBit=false"
  username: root
  password: ",mysql@WSX"
  maximumPoolSize: 8
